one_date_re: ' Copyright (?P<year>[0-9]{4})'
two_date_re: ' Copyright (?P<from>[0-9]{4})-(?P<to>[0-9]{4})'
one_date_format: ' Copyright {year}'
two_date_format: ' Copyright {from}-{to}'
license_file: LICENSE
