name: Generate and Publish Documentation for OSML Model Runner

on:
  workflow_call:

permissions:
    contents: write

jobs:
  docs:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx
          python -m pip install sphinx-autoapi
          python -m pip install sphinx_rtd_theme
          python -m pip install tox tox-gh-actions
      - name: Sphinx build
        run: |
          tox -e docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .tox/docs/tmp/html/
          force_orphan: true
