name: release

on:
  release:
    types: [published]

jobs:
  tox:
    uses: ./.github/workflows/tox.yml
    secrets: inherit
  publish:
    needs: [tox]
    uses: ./.github/workflows/pypi.yml
    secrets: inherit
  docs:
    needs: [publish]
    uses: ./.github/workflows/docs.yml
    secrets: inherit
